version: "3.9"

services:
  api:
    profiles: ["ci"]
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:14.2-alpine"
    restart: always
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: consider_me_compromised
      POSTGRES_USER: pguser
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/initdb.d:/docker-entrypoint-initdb.d/

volumes:
  postgres:
